### ISSUE TITLE
How to Change List of Predefined IP Addresses in "Connect to Device from List"

### ISSUE THREAD

**Issue by IanSC** [vinicioslc/adb-interface-vscode#1]
Is there a settings somewhere to change the list or clear it.
Right now there are a lot of address already on first install.
The most recently selected does not go to the top.

Thanks for the great extension!

**Comment by IanSC** [comment]
Just checked the sources. Sorry, just noticed it's on github.
Turns out it's checking all connected devices, which are my VMs, etc.

**Comment by vinicioslc** [comment]
@IanSC Oh, Thanks !! 
Thankful for your observation.
Anyway i looked what you had done yesterday in your fork, if interested to see your changes on the vscode send a pull request, i be happy in add this enhancement.

**Comment by IanSC** [comment]
@vinicioslc 
I made a pull request (I think). I am new to github and it's my first pull request.
One thing I am not sure about is the "await" on the list of devices. Don't know how to add a value on a future/promise.
Thanks again for making this extension!

**Comment by vinicioslc** [comment]
Hum... ok i will check this pull request and if you 

About promises read this.
https://medium.com/@rafaelvidaurre/truly-understanding-async-await-491dd580500e

await basically means "wait for the execution and give me the return not the promise itself" and on the left we had the temporary variable that will be assigned the value returned.

go to your pull request to continue the discussion.  >> #2
