### ISSUE TITLE
Document how the extension searches the ADB.exe on the system.

### ISSUE THREAD

**Issue by vinicioslc** [vinicioslc/adb-interface-vscode#21]
Explain in readme.md how the extension try to find the `adb.exe` and explain how the option `ADB:📱 Setup custom ADB location` works on README.md.

Requirements: 
- [x] Put the command on commands list section of README.md
- [x] Create another paragraph at end of README.md describing how  `ADB:📱 Setup custom ADB location` works and the strategy behind.
- [x] Found a bug

This issue could be helpful for initial contributors, that want to learn about the extension, but don't know where start, so... start studying the code responsible by find ADB wrapper.

**Comment by moozzyk** [comment]
I am wondering if the custom path is actually ever set. If I read the code correctly here is the code that is getting the path from the UI and is supposed to save it: 

https://github.com/vinicioslc/adb-interface-vscode/blob/24bb5631a2f462409e7c210c067391c5e113876b/src/controllers/adb-path-controller/index.ts#L48-L60

but I don't see the path being actually saved (i.e. there is no call to `this.pathManagerInstance.setFilePath`).

**Comment by vinicioslc** [comment]
Apparently, in addition to documenting you found a bug ahahah, congratulations!
I created a new issue referencing this and also suggested an addition in your pull request (on markdown) to make it perfect.

Thank you for your contribution.

**Comment by moozzyk** [comment]
I updated the PR as suggested. Also I realized that the PR was opened against a wrong repo so created a new PR that now shows up in PRs here.

**Comment by vinicioslc** [comment]
I also noticed this detail about the wrong repo haha, thanks for the contribution!

Oh and also, congratulations on your work at SignalR Swift, i really appreciate your work.

**Comment by moozzyk** [comment]
Thanks!
