### ISSUE TITLE
Error when run ADB: Pick .APK file and install (on current active device)

### ISSUE THREAD

**Issue by fspjonny** [vinicioslc/adb-interface-vscode#29]
Oi, Vinicios Clarindo.

A linha de comando que está sendo usada está colocando um parâmetro "**-d**" antes do comando instale.

Entrando no terminal do VS Code é possível ver o seguinte alerta: 
**Command failed: adb -d install -d -t "D:/Desenvolvimento/Flutter/MyApp/build/app/outputs/flutter-apk/app-release.apk"**

O mesmo comando feito no terminal do VS Code na mão removendo o **-d que está antes do instala**, faz a instalação correta no dispositivo conectado.

A linha de comando correta seria assim: "**adb install -d -t** " e  está assim: "adb **-d** install -d -t ",

Isto está causando o Alerta e não está instalando o .APK

Grande Abraço!

![Anotação 2020-11-14 195054](https://user-images.githubusercontent.com/36781832/99158552-bd7c3480-26b2-11eb-9106-137f9ecf7339.jpg)

**Comment by vinicioslc** [comment]
Opa tudo bem? 

Irei averiguar essa informação, mas você pode enviar um pull request com a alteração de código para eu aceitar, caso não deseje esperar eu alterar o código, pois  ultimamente estou muito corrido na vida pessoal. 

Abraços, e obrigado pelo feedback!

**Comment by vinicioslc** [comment]
@fspjonny eu acabei de testar em meu dispositivo android 10 e ele instalou corretamente, talvez a versão do adb instalado na sua maquina esteja desatualizada, pois, conforme a documentação da google está tudo como seus conformes.
Vou descrever o que cada argumento representa aqui: 

```adb -d``` Faz o adb utilizar o dispositivo atual na USB e causa erro caso possua múltiplos dispositivos android conectados
```install -d``` permite downgrade de versão do apk sendo instalado
```-t``` permite instalar APKs de teste  (quando você gera um apk sem assinatura de release)

Para saber mais sobre os comandos adb você pode consultar a seguinte documentação oficial [abrir aqui](https://developer.android.com/studio/command-line/adb)

**Comment by Mateuss18** [comment]
Eu estou tendo o mesmo problema tambem, eu instalei a ultima versão do ADB porem ainda não funciona.

**Comment by vinicioslc** [comment]
Opa @Mateuss18 você está com as variáveis de ambiente definidas corretamente? 
Ao digitar `adb` no console (estando em qualquer pasta) você tem o retorno do ADB por exemplo o comando `adb devices` lista os dispositivos conectados a sua máquina ?
