### ISSUE TITLE
Allow Custom Port

### ISSUE THREAD

**Issue by yusoofsh** [vinicioslc/adb-interface-vscode#30]
The Android 11 has native wireless debugging and the port always changes.
Could you add an input field for the port instead of just `5555`?

**Comment by yusoofsh** [comment]
Also, the proposed changes would be:
![image](https://user-images.githubusercontent.com/18055365/99770225-16781c80-2b3a-11eb-9362-c09fc725289f.png)

**Comment by vinicioslc** [comment]
Hi ! well this is a great suggestion.
I will make it happen as soon as possible

**Comment by vinicioslc** [comment]
> The Android 11 has native wireless debugging and the port always changes.
> Could you add an input field for the port instead of just `5555`?

I released a new version 0.21.1 that add this feature, i expect it helps.
