### ISSUE TITLE
ADB returned null value

### ISSUE THREAD

**Issue by is-xianglei** [vinicioslc/adb-interface-vscode#32]
Executing `connect to device IP` returns an error message `ADB returns a null value`.
I can be sure that my phone and computer are connected to the same wifi.

**Comment by vinicioslc** [comment]
Thanks for your contribution ! 
Before proceed i need some awnsers,

You allready opened the android device tcpip port ?
For test purposes, you already try to connect over terminal via wifi before try the plugin ?
