### ISSUE TITLE
Unable to dismiss the notification.

### ISSUE THREAD

**Issue by icnahom** [vinicioslc/adb-interface-vscode#4]
Device is connected successfully, but the notification is still showing "Connecting ADB IP". It's not going away..

**Comment by vinicioslc** [comment]
ho im very happy that're using the extension, i will check this.

**Comment by vinicioslc** [comment]
@icnahom i just make a deploy from a new version give a try 👍 ❤️ #5

**Comment by icnahom** [comment]
> @icnahom i just make a deploy from a new version give a try   #5

But now I have to dismiss 2 notification to get connected. It is waiting for me to close the "Connecting through IP" and 
then "Connecting to x.x.x.x" notification just to get connected.

One improvement I liked however is that I don't have to reset the port everytime, good job for that!

**Comment by vinicioslc** [comment]
I will make some improvements in this #6  or if you could contribute Ç, Ç, i will do something like automatically reset attached devices ports when try connect one.
Do you think it can help?
Because it is almost always necessary to have the smartphone ports reset
