### ISSUE TITLE
/bin/sh 1: adb: not found

### ISSUE THREAD

**Issue by sdykae** [vinicioslc/adb-interface-vscode#44]
![image](https://user-images.githubusercontent.com/50224521/142685094-951d7bf4-8110-48f8-ba88-02c06ec44c31.png)

Unable to connect,
Can connect through console though

**Comment by hericles-koelher** [comment]
same here :(

![Captura de tela de 2021-11-24 00-33-50](https://user-images.githubusercontent.com/34146602/143170388-145dd294-dcf1-44b8-9d36-7e441edada48.png)

**Comment by hericles-koelher** [comment]
hey @sdykae if you are on Linux try add this to your PATH variable (you can do something similar on Mac)

```
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

**Comment by vinicioslc** [comment]
@hericles-koelher 
interesting... i can add these locations for search when have the platform tools, before the extension giving up sumon the adb interface.

Sorry my slow response im so busy on fulltime job

**Comment by luckygogreen** [comment]
it is not work on Mac ,
All operations prompt  “Error:Error: ADB not founded in this machine”
adb is fine 
i can contect by
> adb pair 192.168.1.11:76888

**Comment by Anjibupaya** [comment]
> ![image](https://user-images.githubusercontent.com/50224521/142685094-951d7bf4-8110-48f8-ba88-02c06ec44c31.png)
> 
> Unable to connect, Can connect through console though

If this is mac leave zshrc, remove path for adb from this in ~/.zshrc and install android-platform-tools from homebrew instead

`brew install android-platform-tools`

Also after install do `which adb` to verify the location of new adb install is brew or not

**Comment by adds08** [comment]
> ![image](https://user-images.githubusercontent.com/50224521/142685094-951d7bf4-8110-48f8-ba88-02c06ec44c31.png)
> 
> Unable to connect, Can connect through console though

If this is mac leave zshrc, remove path for adb from this in ~/.zshrc and install android-platform-tools from homebrew instead

`brew install android-platform-tools`

Also after install do `which adb` to verify the location of new adb install is brew or not

**Comment by vinicioslc** [comment]
@adds08 first of all a huge THANKs for all this info 
Second, i have short time free to implement this due my main job 

And without intending to bother you, if you have free time, implement some PRs for this feature and request merge, this repository is participating in hacktoberfest https://hacktoberfest.com/participation/ 

with 4 approved prs you can receive a github blouse these 4 prs can be small and incremental just get approved before the 30th and be one of the first 40k

**Comment by vinicioslc** [comment]
@adds08 A Huge THANKs for all this info i expect will help everyone.
