### ISSUE TITLE
it is not work on Mac

### ISSUE THREAD

**Issue by luckygogreen** [vinicioslc/adb-interface-vscode#45]
thank you for all your work, i test on windows it is work !

**but it is not work on Mac ,**
All operations prompt “Error:Error: ADB not founded in this machine”
my adb path is fine

i can contect by
adb pair 192.168.1.11:76888

**Comment by luckygogreen** [comment]
Sorry ,i try in MacAir (M1) not work but work in Macbook Pro(Intel)
so ,it is maybe my macbook problem

**Comment by Anjibupaya** [comment]
It seems that the extension is using bash or zprofile to try and load adb but as per new version (11+) in macos it has switched to zsh. This plugin needs to be updated to use terminal specified by vscode.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/104820127/195568517-35a97bdd-6b01-4d78-8299-18c31f3ad6ff.png">

For workaround add adb paths into  bash that is used by sh but for me that is also not working. Maybe not enough path added. I think the file for this is .zprofile in ~/

**Comment by adds08** [comment]
> thank you for all your work, i test on windows it is work !
> 
> **but it is not work on Mac ,** All operations prompt “Error:Error: ADB not founded in this machine” my adb path is fine
> 
> i can contect by adb pair 192.168.1.11:76888

Similar to issue #44 
Solution is posted hope it helps
https://github.com/vinicioslc/adb-interface-vscode/issues/44#issuecomment-1277426672
