### ISSUE TITLE
Error adb: not found  - Ubuntu 23.04

### ISSUE THREAD

**Issue by nkgiovannivl** [vinicioslc/adb-interface-vscode#76]
Hi All,

I'm trying to setup the adb executable to avoid "Error adb: not found " via command palette, but the extension is not taking into account the change, below my process:

Select the command:

![Screenshot from 2023-10-02 16-41-48](https://github.com/vinicioslc/adb-interface-vscode/assets/48342344/0e504fc6-c55f-44cb-bf76-35095a6eb0b0)

Select ADB executable (Android studio was installed as default)
![Screenshot from 2023-10-02 16-39-42](https://github.com/vinicioslc/adb-interface-vscode/assets/48342344/716a697e-1f3a-41bf-b672-8481c922798a)

Try to use and get the error:
![Screenshot from 2023-10-02 16-39-10](https://github.com/vinicioslc/adb-interface-vscode/assets/48342344/03e0040f-0d2a-475e-9403-75b3c325a499)

So, I don't know my error procedure, thanks!

**Comment by vinicioslc** [comment]
You already exported the adb environment into your .bashrc .profilerc or something similar ?

**Comment by nkgiovannivl** [comment]
> You already exported the adb environment into your .bashrc .profilerc or something similar ?

That was the problem, the ENV PATH to my full adb path was missing, thanks!
