### ISSUE TITLE
Make easy to set ADB path

### ISSUE THREAD

**Issue by jeffnielson** [vinicioslc/adb-interface-vscode#8]
You mentioned:
"For while, you must have ADB at your Enviroment Variables"
Do you plan to fix this?

**Comment by vinicioslc** [comment]
Yep i have plan to implement this as an feature but its hard have free time in my life to do..
Some of requirements are
- Check if has enviroment allready set
    - when not, heck in Android Studio folder for adb are present
    - when not present in Android Studio folder download everthing needed and put at enviroment variables $PATH.
- need to be crossplatform

**Comment by vinicioslc** [comment]
i has added the initial adb resolver module (that makes any checks when calling ADB) but i only had time to implement the search for environment vars and "platform-tools" folder checks , need to implement the platform-tools download process..

**Comment by n8crwlr** [comment]
Hello, i need this for developing on the road. I have access to different machines by using usb-ssd, but i cannot set env vars on every machine.

Can you, please, add a setting for the path to point it directly to my ssd?

Thank you very much :+1:

**Comment by vinicioslc** [comment]
@n8crwlr thanks for suggestion,this is going to be very useful, will the next task to be implemented, ok ?

**Comment by n8crwlr** [comment]
@vinicioslc This would be great! I tried changing all occurences (paths) in plugin code, but it errors as next when requesting device name.

thank you :100:

**Comment by vinicioslc** [comment]
@n8crwlr 
I just released, the new version 0.19.0, with this #12 feature to select custom ADB path.
